name: Deploy to WP Engine
on:
  push:
    branches:
      - opt-performance
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Running Page Speed Insights
      uses: jakepartusch/psi-action@v1.3
      id: psi
      with:
        url: "https://reade.wpengine.com/"
        threshold: 96
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}