name: Page Speed Checks
on:
  push:
    branches:
      - test-qa
jobs:
  home:
    runs-on: ubuntu-latest  
    steps:
    - name: home-dsk
      uses: jakepartusch/psi-action@v1.3
      id: home-dsk
      with:
        url: "https://reade.wpengine.com/"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: home-mbl
      uses: jakepartusch/psi-action@v1.3
      id: home-mbl
      with:
        url: "https://reade.wpengine.com/"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  services:
    runs-on: ubuntu-latest  
    steps:
    - name: services-dsk
      uses: jakepartusch/psi-action@v1.3
      id: services-dsk
      with:
        url: "https://reade.wpengine.com/services"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: services-mbl
      uses: jakepartusch/psi-action@v1.3
      id: services-mbl
      with:
        url: "https://reade.wpengine.com/services"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  global-sourcing:
    runs-on: ubuntu-latest  
    steps:
    - name: global-sourcing-dsk
      uses: jakepartusch/psi-action@v1.3
      id: global-sourcing-dsk
      with:
        url: "https://reade.wpengine.com/services/global-sourcing"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: global-sourcing-mbl
      uses: jakepartusch/psi-action@v1.3
      id: global-sourcing-mbl
      with:
        url: "https://reade.wpengine.com/services/global-sourcing"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  toll-processing:
    runs-on: ubuntu-latest  
    steps:
    - name: toll-processing-dsk
      uses: jakepartusch/psi-action@v1.3
      id: toll-processing-dsk
      with:
        url: "https://reade.wpengine.com/services/toll-processing"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: toll-processing-mbl
      uses: jakepartusch/psi-action@v1.3
      id: toll-processing-mbl
      with:
        url: "https://reade.wpengine.com/services/toll-processing"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  toll-packaging:
    runs-on: ubuntu-latest  
    steps:
    - name: toll-packaging-dsk
      uses: jakepartusch/psi-action@v1.3
      id: toll-packaging-dsk
      with:
        url: "https://reade.wpengine.com/services/toll-packaging"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: toll-packaging-mbl
      uses: jakepartusch/psi-action@v1.3
      id: toll-packaging-mbl
      with:
        url: "https://reade.wpengine.com/services/toll-packaging"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  about-us:
    runs-on: ubuntu-latest  
    steps:
    - name: about-us-dsk
      uses: jakepartusch/psi-action@v1.3
      id: about-us-dsk
      with:
        url: "https://reade.wpengine.com/about-us"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: about-us-mbl
      uses: jakepartusch/psi-action@v1.3
      id: about-us-mbl
      with:
        url: "https://reade.wpengine.com/about-us"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  history:
    runs-on: ubuntu-latest  
    steps:
    - name: history-dsk
      uses: jakepartusch/psi-action@v1.3
      id: history-dsk
      with:
        url: "https://reade.wpengine.com/about-us/history"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: history-mbl
      uses: jakepartusch/psi-action@v1.3
      id: history-mbl
      with:
        url: "https://reade.wpengine.com/about-us/history"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  terms-conditions-of-sale:
    runs-on: ubuntu-latest  
    steps:
    - name: terms-conditions-of-sale-dsk
      uses: jakepartusch/psi-action@v1.3
      id: terms-conditions-of-sale-dsk
      with:
        url: "https://reade.wpengine.com/about-us/terms-conditions-of-sale"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: terms-conditions-of-sale-mbl
      uses: jakepartusch/psi-action@v1.3
      id: terms-conditions-of-sale-mbl
      with:
        url: "https://reade.wpengine.com/about-us/terms-conditions-of-sale"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  faqs:
    runs-on: ubuntu-latest  
    steps:
    - name: faqs-dsk
      uses: jakepartusch/psi-action@v1.3
      id: faqs-dsk
      with:
        url: "https://reade.wpengine.com/about-us/faqs"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: faqs-mbl
      uses: jakepartusch/psi-action@v1.3
      id: faqs-mbl
      with:
        url: "https://reade.wpengine.com/about-us/faqs"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  careers:
    runs-on: ubuntu-latest  
    steps:
    - name: careers-dsk
      uses: jakepartusch/psi-action@v1.3
      id: careers-dsk
      with:
        url: "https://reade.wpengine.com/about-us/careers"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: careers-mbl
      uses: jakepartusch/psi-action@v1.3
      id: careers-mbl
      with:
        url: "https://reade.wpengine.com/about-us/careers"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  service-disabled-veteran-owned-small-business:
    runs-on: ubuntu-latest  
    steps:
    - name: service-disabled-veteran-owned-small-business-dsk
      uses: jakepartusch/psi-action@v1.3
      id: service-disabled-veteran-owned-small-business-dsk
      with:
        url: "https://reade.wpengine.com/about-us/service-disabled-veteran-owned-small-business"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: service-disabled-veteran-owned-small-business-mbl
      uses: jakepartusch/psi-action@v1.3
      id: service-disabled-veteran-owned-small-business-mbl
      with:
        url: "https://reade.wpengine.com/about-us/service-disabled-veteran-owned-small-business"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  industries-served:
    runs-on: ubuntu-latest  
    steps:
    - name: industries-served-dsk
      uses: jakepartusch/psi-action@v1.3
      id: industries-served-dsk
      with:
        url: "https://reade.wpengine.com/about-us/industries-served"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: industries-served-mbl
      uses: jakepartusch/psi-action@v1.3
      id: industries-served-mbl
      with:
        url: "https://reade.wpengine.com/about-us/industries-served"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  quality-at-reade:
    runs-on: ubuntu-latest  
    steps:
    - name: quality-at-reade-dsk
      uses: jakepartusch/psi-action@v1.3
      id: quality-at-reade-dsk
      with:
        url: "https://reade.wpengine.com/about-us/quality-at-reade"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: quality-at-reade-mbl
      uses: jakepartusch/psi-action@v1.3
      id: quality-at-reade-mbl
      with:
        url: "https://reade.wpengine.com/about-us/quality-at-reade"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  leadership:
    runs-on: ubuntu-latest  
    steps:
    - name: leadership-dsk
      uses: jakepartusch/psi-action@v1.3
      id: leadership-dsk
      with:
        url: "https://reade.wpengine.com/about-us/leadership"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: leadership-mbl
      uses: jakepartusch/psi-action@v1.3
      id: leadership-mbl
      with:
        url: "https://reade.wpengine.com/about-us/leadership"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  contact:
    runs-on: ubuntu-latest  
    steps:
    - name: contact-dsk
      uses: jakepartusch/psi-action@v1.3
      id: contact-dsk
      with:
        url: "https://reade.wpengine.com/contact/"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: contact-mbl
      uses: jakepartusch/psi-action@v1.3
      id: contact-mbl
      with:
        url: "https://reade.wpengine.com/contact/"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  partner-with-us:
    runs-on: ubuntu-latest  
    steps:
    - name: partner-with-us-dsk
      uses: jakepartusch/psi-action@v1.3
      id: partner-with-us-dsk
      with:
        url: "https://reade.wpengine.com/partner-with-us/"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: partner-with-us-mbl
      uses: jakepartusch/psi-action@v1.3
      id: partner-with-us-mbl
      with:
        url: "https://reade.wpengine.com/partner-with-us/"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  terms-of-services:
    runs-on: ubuntu-latest  
    steps:
    - name: terms-of-services-dsk
      uses: jakepartusch/psi-action@v1.3
      id: terms-of-services-dsk
      with:
        url: "https://reade.wpengine.com/terms-of-services/"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: terms-of-services-mbl
      uses: jakepartusch/psi-action@v1.3
      id: terms-of-services-mbl
      with:
        url: "https://reade.wpengine.com/terms-of-services/"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  products:
    runs-on: ubuntu-latest  
    steps:
    - name: products-dsk
      uses: jakepartusch/psi-action@v1.3
      id: products-dsk
      with:
        url: "https://reade.wpengine.com/products/"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: products-mbl
      uses: jakepartusch/psi-action@v1.3
      id: products-mbl
      with:
        url: "https://reade.wpengine.com/products/"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  sustainable-products:
    runs-on: ubuntu-latest  
    steps:
    - name: sustainable-products-dsk
      uses: jakepartusch/psi-action@v1.3
      id: sustainable-products-dsk
      with:
        url: "https://reade.wpengine.com/sustainable-products/"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: sustainable-products-mbl
      uses: jakepartusch/psi-action@v1.3
      id: sustainable-products-mbl
      with:
        url: "https://reade.wpengine.com/sustainable-products/"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
  news:
    runs-on: ubuntu-latest  
    steps:
    - name: news-dsk
      uses: jakepartusch/psi-action@v1.3
      id: news-dsk
      with:
        url: "https://reade.wpengine.com/news/"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: news-mbl
      uses: jakepartusch/psi-action@v1.3
      id: news-mbl
      with:
        url: "https://reade.wpengine.com/news/"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}