name: Page Speed Checks
on:
  push:
    branches:
      - test-qa
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: sustainable-products-mbl
      uses: jakepartusch/psi-action@v1.3
      id: sustainable-products-mbl
      with:
        url: "https://reade.wpengine.com/sustainable-products/"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
    - name: sustainable-products-dsk
      uses: jakepartusch/psi-action@v1.3
      id: sustainable-products-dsk
      with:
        url: "https://reade.wpengine.com/sustainable-products/"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    - name: home-mbl
      uses: jakepartusch/psi-action@v1.3
      id: home-mbl
      with:
        url: "https://reade.wpengine.com/"
        threshold: 80
        strategy: mobile
        key: ${{ secrets.PSI_APIKEY }}
    - name: home-dsk
      uses: jakepartusch/psi-action@v1.3
      id: home-dsk
      with:
        url: "https://reade.wpengine.com/"
        threshold: 80
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}